export const BASE_SECTION = {
    title: 'New Section',
    description: 'This is a section',
    imgUrl: null,
    backgroundImg: null,
    backgroundColor: '#8367C7',
    position: 'top',
    height: 300,
    paddingV: 16,
    paddingH: 8,
    textAlign: 'center',
    titleFontFamily: 'Roboto',
    titleFontSize: 32,
    titleColor: '#F0FFF1',
    descriptionFontFamily: 'Roboto',
    descriptionFontSize: 32,
    descriptionColor: '#F0FFF1',
};